### ISSUE TITLE
Scroll support

### ISSUE THREAD

**Issue by FANMixco** [gregstoll/UniversalWrapPanel#1]
Hi, I really love your work, thanks man! I have a question or it's a bug, do you know how I can use a scrollbar in this configuration:

```
<ScrollViewer>
<UniversalWrapPanel:UniversalWrapPanel HorizontalAlignment="Center" Orientation="Horizontal">
</UniversalWrapPanel:UniversalWrapPanel>
</ScrollViewer>
```

Sometimes, I have too many elements that finally, it's impossible to display all of them and I cannot scroll it vertically, thanks for any help or suggestion.

**Comment by gregstoll** [comment]
Thanks!

Hmm, that seems like it should work.  If you set an explicit Height on the ScrollViewer, does that change anything?  If not, what do you see in this case?  Can you attach a screenshot?
